// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AI configuration as the client is allowed to see it — note there is no key
 * here. The key is written once and never read back out of the host.
 */
export type AiSettings = { 
/**
 * An OpenAI-compatible base URL, e.g. `http://127.0.0.1:8080/v1` for
 * llama.cpp, or a hosted provider while the school still has internet.
 */
base_url?: string, model: string, 
/**
 * Whether a key is stored, so the UI can say "set" without ever showing it.
 */
has_key: boolean, 
/**
 * False until the endpoint actually answers.
 */
reachable: boolean, 
/**
 * A separate Google key, used only for finding papers online and locating
 * figures inside them. Without it the paper creator falls back to uploads
 * and hand-drawn crops.
 */
has_google_key: boolean, google_model: string, };
