// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * The role requested by a particular app binary. The server still checks the
 * stored account role on every protected route.
 */
export type AppLoginRequest = { username: string, password: string, device_label: string | null, expected_role: Role, };
