// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssignmentStatus } from "./AssignmentStatus";

export type Assignment = { id: string, classroom_id: string, classroom_name: string, title: string, instructions: string, due_at: string | null, max_points: number, 
/**
 * Configurable grading definition. Kept as JSON so a school can use points,
 * percentages, letters, or a rubric without another schema migration.
 */
grading_scheme: unknown, status: AssignmentStatus, created_at: string, updated_at: string, };
