// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveSessionTaskKind } from "./LiveSessionTaskKind";

export type AssignLiveSessionTaskRequest = { kind: LiveSessionTaskKind, target_id: string | null, title: string, instructions: string, };
