// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttendanceStatus } from "./AttendanceStatus";

export type AttendanceRecord = { student_id: string, student_name: string, status: AttendanceStatus | null, note: string, 
/**
 * A recent login is a suggestion only; the teacher remains authoritative.
 */
checked_in: boolean, };
