// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BootstrapTeacherRequest = { username: string, display_name: string, password: string, 
/**
 * Eight-digit setup PIN printed by the host while no active teacher exists.
 */
bootstrap_pin: string, };
