// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type BootstrapTeacherResponse = { user: User, 
/**
 * Shown exactly once. Only its Argon2id hash is stored.
 */
recovery_code: string, };
