// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardOrigin } from "./CardOrigin";

export type Card = { id: string, deck_node_id: string, front: string, back: string, 
/**
 * Which note or PDF this card came from, so a student can jump back to context.
 */
source_node_id: string | null, source_excerpt: string | null, generated_by: CardOrigin, };
