// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";

export type ChatRequest = { messages: Array<ChatMessage>, 
/**
 * Optional note text the student wants the assistant to work from.
 */
context?: string, 
/**
 * Optional response budget for structured, long-form tasks such as papers.
 * Ordinary chat leaves this unset so provider defaults remain unchanged.
 */
max_output_tokens?: number, };
