// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Classroom = { id: string, name: string, subject_code: string | null, description: string, color: string, owner_teacher_id: string, owner_teacher_name: string, enrolment_code: string, student_count: number, created_at: string, };
