// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Classroom } from "./Classroom";
import type { User } from "./User";

export type ClassroomRoster = { classroom: Classroom, students: Array<User>, };
