// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateStudentRequest = { classroom_id: string, username: string, display_name: string, grade_level: string | null, section: string | null, roll_number: string | null, };
