// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type CreateStudentResponse = { user: User, 
/**
 * Four-digit, one-time PIN shown once to the teacher.
 */
temporary_password: string, 
/**
 * A separate rotating recovery code. Only its Argon2id hash is stored.
 */
recovery_code: string, };
