// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateAssignmentRequest = { classroom_id: string, title: string, instructions: string, due_at: string | null, max_points: number, grading_scheme: unknown, publish: boolean, };
