// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from "./NodeKind";

export type CreateNodeRequest = { parent_id: string | null, classroom_id: string | null, name: string, kind: NodeKind, icon: string | null, };
