// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCardRequest = { front: string, back: string, source_node_id: string | null, source_excerpt: string | null, };
