// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type CreateUserRequest = { username: string, display_name: string, password: string, role: Role, };
