// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DashboardStats = { students: bigint, classrooms: bigint, pending_submissions: bigint, ungraded_submissions: bigint, present_today: bigint, };
