// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DayTotal = { 
/**
 * `YYYY-MM-DD` in the host's local timezone — the school day, not UTC.
 */
day: string, seconds: bigint, };
