// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeleteTeacherRequest = { 
/**
 * The signed-in teacher confirms this sensitive action with their password.
 */
current_password: string, };
