// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuizDeliveryKind } from "./QuizDeliveryKind";

export type DeliverQuizRequest = { kind: QuizDeliveryKind, live_session_id: string | null, opens_at: string | null, due_at: string | null, };
