// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileMeta = { node_id: string, orig_name: string, bytes: bigint, mime: string, };
