// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenerateCardsRequest = { source_node_id: string, 
/**
 * The passage the student selected. Capped host-side before it reaches the model.
 */
excerpt: string, count: number, deck_node_id: string, };
