// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GradeChange = { id: string, previous: unknown, current: unknown, changed_at: string, };
