// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HealthResponse = { ok: boolean, version: string, 
/**
 * False when `llama-server` is not running, so the UI can hide AI actions
 * instead of offering a button that fails.
 */
ai_available: boolean, };
