// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveSession } from "./LiveSession";
import type { LiveSessionParticipant } from "./LiveSessionParticipant";
import type { LiveSessionTask } from "./LiveSessionTask";
import type { LiveSessionTaskProgress } from "./LiveSessionTaskProgress";

export type LiveSessionDetails = { session: LiveSession, participants: Array<LiveSessionParticipant>, tasks: Array<LiveSessionTask>, task_progress: Array<LiveSessionTaskProgress>, };
