// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveSessionTask } from "./LiveSessionTask";
import type { LiveSessionTaskParticipantProgress } from "./LiveSessionTaskParticipantProgress";

export type LiveSessionTaskProgress = { task: LiveSessionTask, participants: Array<LiveSessionTaskParticipantProgress>, };
