// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveSessionTaskKind } from "./LiveSessionTaskKind";

export type LiveSessionTask = { id: string, revision: number, kind: LiveSessionTaskKind, target_id: string | null, title: string, instructions: string, created_at: string, };
