// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveSessionResult } from "./LiveSessionResult";
import type { LiveSessionTaskAcknowledgement } from "./LiveSessionTaskAcknowledgement";

export type LiveSessionTaskParticipantProgress = { student_id: string, student_name: string, state: LiveSessionTaskAcknowledgement | null, result: LiveSessionResult | null, };
