// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveSessionResult = { score: number, elapsed_seconds: number, task_revision: number | null, submitted_at: string, };
