// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveSessionResult } from "./LiveSessionResult";

export type LiveSessionParticipant = { student_id: string, student_name: string, joined_at: string, result: LiveSessionResult | null, };
