// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveSession = { id: string, classroom_id: string, classroom_name: string, module_id: string, module_name: string, duration_minutes: number, join_code: string, starts_at: string, ends_at: string, ended_at: string | null, };
