// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveSession } from "./LiveSession";

export type LiveSessionHistoryItem = { session: LiveSession, participant_count: number, completed_count: number, };
