// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveSessionTaskState } from "./LiveSessionTaskState";

export type LiveSessionTaskAcknowledgement = { revision: number, state: LiveSessionTaskState, updated_at: string, };
