// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginRequest = { username: string, password: string, 
/**
 * Free text shown to the teacher in the sessions list, e.g. "Lab PC 4".
 */
device_label: string | null, };
