// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionKind } from "./SessionKind";

export type LogSessionRequest = { node_id: string | null, started_at: string, ended_at: string, planned_seconds: bigint, actual_seconds: bigint, kind: SessionKind, interrupted: boolean, };
