// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every item a student owns is a node in one tree: subjects and topics are
 * `Folder`s, everything else is a leaf. There is no separate "file explorer" —
 * the subject organizer *is* this tree.
 */
export type NodeKind = "folder" | "note" | "pdf" | "deck";
