// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from "./NodeKind";

export type Node = { id: string, 
/**
 * `None` means this node belongs to the shared class library that the
 * teacher curates and every student can read.
 */
owner_id: string | null, parent_id: string | null, classroom_id: string | null, name: string, kind: NodeKind, 
/**
 * Sort key among siblings. Sparse (steps of 1024) so a drag-drop reorder
 * usually rewrites one row instead of the whole sibling set.
 */
position: bigint, icon: string | null, created_at: string, updated_at: string, };
