// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteBody = { 
/**
 * TipTap/ProseMirror document JSON — the source of truth for rendering.
 */
doc_json: unknown, 
/**
 * Flattened text, kept in sync on every save. Powers FTS5 search and is
 * what gets sent to the local model — never send `doc_json` to the AI.
 */
plaintext: string, updated_at: string, };
