// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rendered page on its way to figure detection. Discarded once the boxes
 * come back; page images are never stored.
 */
export type PaperPageImage = { page: number, 
/**
 * Base64 JPEG, without a data-URL prefix.
 */
jpeg_base64: string, };
