// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One past paper found online. Nothing is downloaded until the teacher picks
 * one, which is also what keeps Cinder clear of automated crawling.
 */
export type PaperCandidate = { title: string, url: string, board: string, year: string, session: string, variant: string, snippet: string, };
