// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A figure located on a rendered page. `box_2d` is `[ymin, xmin, ymax, xmax]`,
 * each normalised to 0–1000 of the supplied image, so the client can crop
 * without the model knowing the page's pixel size.
 */
export type PaperFigure = { page: number, box_2d: [number, number, number, number], caption: string, alt: string, };
