// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of a source paper the teacher intends to reuse. Boards allow
 * classroom use on their own terms, so the stricter two modes carry a recorded
 * confirmation rather than being silently equivalent.
 */
export type PaperSourceMode = "adapt" | "excerpt" | "full_page";
