// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaperSourceMode } from "./PaperSourceMode";

/**
 * A stored paper. The marking scheme travels with it because every route that
 * returns this type is teacher-only; student-facing work is produced by
 * publishing an assignment or a quiz, never by serialising this.
 */
export type QuestionPaper = { id: string, owner_id: string, classroom_id: string | null, title: string, subject: string, board: string, syllabus_code: string, difficulty: number, source_mode: PaperSourceMode, rights_confirmed: boolean, spec: unknown, scheme: unknown, sources: unknown, advanced: unknown, created_at: string, updated_at: string, };
