// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuizQuestion } from "./QuizQuestion";

export type Quiz = { id: string, classroom_id: string, classroom_name: string, title: string, instructions: string, time_limit_minutes: number | null, archived: boolean, published_version: number | null, questions: Array<QuizQuestion>, updated_at: string, };
