// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuizQuestionStatistic } from "./QuizQuestionStatistic";

export type QuizStatistics = { assigned_count: number, started_count: number, submitted_count: number, graded_count: number, highest: number | null, lowest: number | null, mean: number | null, median: number | null, lower_quartile: number | null, upper_quartile: number | null, distribution: Array<number>, questions: Array<QuizQuestionStatistic>, most_correct_question_id: string | null, most_incorrect_question_id: string | null, };
