// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuizQuestionStatistic = { question_id: string, prompt: string, graded_count: number, correct_percent: number, partial_percent: number, };
