// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuizDelivery } from "./QuizDelivery";
import type { QuizResponse } from "./QuizResponse";
import type { StudentQuizQuestion } from "./StudentQuizQuestion";

export type QuizAttempt = { id: string, student_id: string, student_name: string, delivery: QuizDelivery, questions: Array<StudentQuizQuestion>, responses: Array<QuizResponse>, started_at: string, expires_at: string | null, submitted_at: string | null, score: number | null, max_points: number, manual_grading_complete: boolean, released: boolean, server_now: string, };
