// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuizDeliveryKind } from "./QuizDeliveryKind";

export type QuizDelivery = { id: string, quiz_id: string, version_id: string, classroom_id: string, classroom_name: string, title: string, instructions: string, kind: QuizDeliveryKind, time_limit_minutes: number | null, total_points: number, opens_at: string | null, due_at: string | null, results_released_at: string | null, attempt_id: string | null, attempt_state: string | null, };
