// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuizResponse = { question_id: string, answer: unknown, points: number | null, feedback: string, correct: boolean | null, canonical_answer: unknown | null, };
