// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterTeacherRequest = { username: string, display_name: string, password: string, 
/**
 * One-time PIN generated by an already signed-in teacher.
 */
invite_pin: string, };
