// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewState = { due: string, 
/**
 * Current interval in days. (Named `stability` for FSRS compatibility.)
 */
stability: number, 
/**
 * SM-2 ease factor, clamped to `MIN_EASE`.
 */
difficulty: number, reps: bigint, lapses: bigint, last_review: string | null, };
