// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveGradeRequest = { points: number | null, grade_label: string | null, feedback: string, publish: boolean, };
