// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuizQuestionInput } from "./QuizQuestionInput";

export type SaveQuizRequest = { classroom_id: string, title: string, instructions: string, time_limit_minutes: number | null, questions: Array<QuizQuestionInput>, };
