// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaperSourceMode } from "./PaperSourceMode";

export type SaveQuestionPaperRequest = { classroom_id: string | null, title: string, subject: string, board: string, syllabus_code: string, difficulty: number, source_mode: PaperSourceMode, rights_confirmed: boolean, spec: unknown, scheme: unknown, sources: unknown, advanced: unknown, };
