// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveNoteRequest = { doc_json: unknown, plaintext: string, 
/**
 * The `updated_at` the client last saw. The host rejects the write with
 * `409` if the row moved on, so a stale offline outbox cannot clobber a
 * newer edit without the student being told.
 */
base_updated_at: string | null, };
