// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveAiSettings = { base_url?: string, model: string, 
/**
 * Absent leaves the stored key alone; empty string clears it.
 */
api_key?: string, 
/**
 * Same rule as `api_key`, for the Google key.
 */
google_key?: string, google_model?: string, };
