// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttendanceStatus } from "./AttendanceStatus";

export type SaveAttendanceRequest = { student_id: string, status: AttendanceStatus, note: string, };
