// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchHit = { node_id: string, name: string, 
/**
 * FTS5 snippet of the student's own prose, with matches wrapped in
 * [`MATCH_START`]/[`MATCH_END`] control characters.
 *
 * Deliberately not HTML: the client renders this as text and builds its own
 * highlight elements, so a note containing markup cannot execute anywhere.
 */
snippet: string, };
