// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StartLiveSessionRequest = { classroom_id: string, module_id: string, module_name: string, duration_minutes: number, };
