// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayTotal } from "./DayTotal";
import type { SubjectTotal } from "./SubjectTotal";

export type StudySummary = { total_seconds: bigint, sessions_started: bigint, sessions_completed: bigint, current_streak_days: bigint, by_subject: Array<SubjectTotal>, by_day: Array<DayTotal>, };
