// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionKind } from "./SessionKind";

/**
 * One logged stretch of study. This table is the project's impact evidence —
 * every minute is attributed to a subject via `node_id`.
 */
export type StudySession = { id: string, user_id: string, node_id: string | null, started_at: string, ended_at: string, planned_seconds: bigint, actual_seconds: bigint, kind: SessionKind, 
/**
 * True when the student stopped early. Kept because "started 40 sessions,
 * finished 12" is a more honest signal than raw hours.
 */
interrupted: boolean, };
