// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuizQuestionKind } from "./QuizQuestionKind";

export type StudentQuizQuestion = { id: string, position: number, kind: QuizQuestionKind, prompt: string, options: Array<string>, max_points: number, required: boolean, };
