// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmitWorkRequest = { doc_json: unknown, plaintext: string, change_note: string | null, };
