// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmissionVersion = { id: string, version_number: bigint, doc_json: unknown, plaintext: string, change_note: string | null, late: boolean, created_at: string, };
