// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Grade } from "./Grade";
import type { SubmissionStatus } from "./SubmissionStatus";
import type { SubmissionVersion } from "./SubmissionVersion";

export type Submission = { id: string, assignment_id: string, assignment_title: string, student_id: string, student_name: string, status: SubmissionStatus, version: SubmissionVersion | null, grade: Grade | null, submitted_at: string | null, updated_at: string, };
