// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";

export type TreeResponse = { 
/**
 * Flat list. The client builds the tree from `parent_id`; sending it flat
 * keeps the payload small and lets the UI virtualize long subject lists.
 */
nodes: Array<Node>, };
