// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateClassroomRequest = { name: string, subject_code: string | null, description: string, color: string, };
