// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every field optional: this is a partial update used for rename, move and reorder.
 */
export type UpdateNodeRequest = { 
/**
 * Every field is `#[ts(optional)]` so the generated TypeScript emits `name?:`
 * rather than `name:`. That is not cosmetic — with required keys a caller
 * doing a rename would be forced to pass `parent_id: null`, which means
 * "move to the root", silently relocating the node it meant to rename.
 */
name?: string, 
/**
 * `Some(None)` moves the node to the root; `None` leaves the parent alone.
 *
 * The custom deserializer is load-bearing. Plain serde maps both an absent
 * field and an explicit `null` to `None`, which would make "move to the
 * root" unexpressible — the request would be accepted and silently ignored.
 */
parent_id?: string | null, position?: bigint, icon?: string, };
