// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssignmentStatus } from "./AssignmentStatus";

export type UpdateAssignmentRequest = { classroom_id: string, title: string, instructions: string, due_at: string | null, max_points: number, grading_scheme: unknown, status: AssignmentStatus, };
