// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type User = { id: string, username: string, display_name: string, role: Role, grade_level: string | null, section: string | null, roll_number: string | null, 
/**
 * Temporary credentials are replaced on the student's first successful login.
 */
must_change_password: boolean, created_at: string, };
